# Generated by Django 6.0.1 on 2026-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('query_count', models.IntegerField(default=0)),
                ('last_queried', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Favorite City',
                'verbose_name_plural': 'Favorite Cities',
                'ordering': ['-query_count', 'city'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('rain', 'Rain'), ('storm', 'Storm'), ('snow', 'Snow'), ('heat', 'Extreme Heat'), ('cold', 'Extreme Cold'), ('wind', 'High Wind')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('query_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
            ],
            options={
                'verbose_name': 'Weather Query',
                'verbose_name_plural': 'Weather Queries',
                'ordering': ['-query_time'],
                'indexes': [models.Index(fields=['-query_time'], name='weatherapp__query_t_544834_idx'), models.Index(fields=['city', '-query_time'], name='weatherapp__city_21253a_idx')],
            },
        ),
    ]
